// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmddwhmyenbukgwdjlex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtZGR3aG15ZW5idWtnd2RqbGV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzA5OTksImV4cCI6MjA1OTcwNjk5OX0.OGPAmK3Rd8UbCUBqtLE8YNB3sZ82DRD3tyioi1tZYzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);